export { default as NoMatch } from './NoMatch';
export { default as PaymentPortal } from './PaymentPortal';
export { default as PaymentPage } from './PaymentPage';
export { default as EventsPage } from './EventsPage';
export { default as LandingPage } from './LandingPage';
export { default as Login } from './Login';
export { default as AboutUs } from './AboutUs';
export { default as Contact } from './Contact';
export { default as AcademicsPage } from './AcademicsPage';
